image_width: 1280
image_height: 720
camera_name: /rgb
camera_matrix:
  rows: 3
  cols: 3
  data: [1030.80428,    0.     ,  637.53454,
            0.     , 1026.07132,  352.45846,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.080302, -0.136590, -0.005660, 0.001299, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1043.22287,    0.     ,  639.0702 ,    0.     ,
            0.     , 1039.39314,  349.30431,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
