image_width: 1280
image_height: 720
camera_name: /oak2/rgb
camera_matrix:
  rows: 3
  cols: 3
  data: [1031.26786,    0.     ,  614.32441,
            0.     , 1031.83665,  355.25599,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.073189, -0.112241, 0.001096, -0.003409, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1042.69115,    0.     ,  610.00818,    0.     ,
            0.     , 1047.16915,  355.87082,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]