image_width: 1280
image_height: 720
camera_name: /rgb
camera_matrix:
  rows: 3
  cols: 3
  data: [1090.24403,    0.     ,  644.01514,
            0.     , 1091.664  ,  323.37736,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.104758, -0.187619, -0.008771, 0.004204, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1108.02462,    0.     ,  649.05559,    0.     ,
            0.     , 1110.87874,  318.29473,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
