/oak1:
  ros__parameters:
    camera:
      i_mx_id: 19443010E16B271300
      i_nn_type: none
      i_pipeline_type: RGB
      i_publish_tf_from_calibration: True
      i_tf_base_frame: oak1
      i_restart_on_diagnostics_error: True
    pipeline_gen:
      i_enable_imu: False
    rgb:
      i_resolution: 1080P   # 4K
      i_height: 720
      i_width: 1280
      i_enable_nn: false
      i_calibration_file: "package://follow_traj_moveit/config/calibration/oak2_rgb.yaml"

/oak1/apriltag:
  ros__parameters:
    image_transport: raw
    family: "36h11"
    size: 0.15

    tag:
      ids: [0]
      frames: ["table2_from_oak1"]
      sizes: [0.15]

    pose_estimation_method: "pnp"

    detector:
      threads: 1          # number of threads
      decimate: 2.0       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: True           # snap to strong gradients
      sharpening: 0.25    # sharpening of decoded images
      debug: False            # write additional debugging images to current working directory
    
    max_hamming: 0
    profile: false

/oak2:
  ros__parameters:
    camera:
      i_mx_id: 1944301001C62A1300
      i_nn_type: none
      i_pipeline_type: RGB
      i_publish_tf_from_calibration: True
      i_tf_base_frame: oak2
      i_restart_on_diagnostics_error: True
    pipeline_gen:
      i_enable_imu: False
    rgb:
      i_resolution: 1080P   # 4K
      i_height: 720
      i_width: 1280
      i_enable_nn: false
      i_calibration_file: "package://follow_traj_moveit/config/calibration/oak2_rgb.yaml"

/oak2/apriltag:
  ros__parameters:
    image_transport: raw
    family: "36h11"
    size: 0.15

    tag:
      ids: [0]
      frames: ["table2_from_oak2"]
      sizes: [0.15]

    pose_estimation_method: "pnp"

    detector:
      threads: 1          # number of threads
      decimate: 2.0       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: True           # snap to strong gradients
      sharpening: 0.25    # sharpening of decoded images
      debug: False            # write additional debugging images to current working directory
    
    max_hamming: 0
    profile: false

/oak3:
  ros__parameters:
    camera:
      i_mx_id: 1844301041B7321300
      i_nn_type: none
      i_pipeline_type: RGB
      i_publish_tf_from_calibration: True
      i_tf_base_frame: oak3
      i_restart_on_diagnostics_error: True
    pipeline_gen:
      i_enable_imu: False
    rgb:
      i_resolution: 1080P   # 4K
      i_height: 720
      i_width: 1280
      i_enable_nn: false
      i_calibration_file: "package://follow_traj_moveit/config/calibration/oak2_rgb.yaml"

/oak3/apriltag:
  ros__parameters:
    image_transport: raw
    family: "36h11"
    size: 0.15

    tag:
      ids: [0]
      frames: ["table2_from_oak3"]
      sizes: [0.15]

    pose_estimation_method: "pnp"

    detector:
      threads: 1          # number of threads
      decimate: 2.0       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: True           # snap to strong gradients
      sharpening: 0.25    # sharpening of decoded images
      debug: False            # write additional debugging images to current working directory
    
    max_hamming: 0
    profile: false
